import { FormEvent, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import api from '../api';

const initial = { engineTemperature: '90', engineOilLevel: 'normal', engineRpm: '800', batteryVoltage: '12.6', batteryHealth: '90', fuelLevel: '50', averageFuelEfficiency: '', brakeCondition: '90', frontLeft: '32', frontRight: '32', rearLeft: '32', rearRight: '32', tyreWear: '20', coolantLevel: 'normal', currentOdometer: '', lastServiceDate: '' };
function InspectionPage() {
  const { id } = useParams(); const navigate = useNavigate(); const [values, setValues] = useState(initial); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [saving, setSaving] = useState(false);
  const update = (key: keyof typeof initial, value: string) => setValues({ ...values, [key]: value });
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); setSuccess(''); setSaving(true); try { await api.post('/health-readings', { vehicleId: id, engineTemperature: Number(values.engineTemperature), engineOilLevel: values.engineOilLevel, engineRpm: Number(values.engineRpm), batteryVoltage: Number(values.batteryVoltage), batteryHealth: Number(values.batteryHealth), fuelLevel: Number(values.fuelLevel), averageFuelEfficiency: Number(values.averageFuelEfficiency), brakeCondition: Number(values.brakeCondition), tyrePressure: { fl: Number(values.frontLeft), fr: Number(values.frontRight), rl: Number(values.rearLeft), rr: Number(values.rearRight) }, tyreWear: Number(values.tyreWear), coolantLevel: values.coolantLevel, currentOdometer: Number(values.currentOdometer), lastServiceDate: values.lastServiceDate }); setSuccess('Inspection saved successfully.'); window.setTimeout(() => navigate(`/vehicles/${id}`), 500); } catch (err: any) { setError(err.response?.data?.error || 'Unable to save inspection. Please review the required values.'); } finally { setSaving(false); } };
  const field = (key: keyof typeof initial, label: string, type = 'number', step = 'any') => <label key={key} className="text-sm text-slate-300">{label}<input required type={type} min={type === 'number' ? 0 : undefined} step={type === 'number' ? step : undefined} value={values[key]} onChange={e => update(key, e.target.value)} className="input" /></label>;
  return <main className="min-h-screen bg-slate-950 px-6 py-10 text-slate-100"><form onSubmit={submit} className="mx-auto max-w-5xl"><Link to={`/vehicles/${id}`} className="text-cyan-300">← Vehicle dashboard</Link><p className="mt-6 text-sm uppercase tracking-[.3em] text-cyan-400">Workshop record</p><h1 className="mt-2 text-4xl font-semibold">Vehicle Inspection</h1><p className="mt-3 text-slate-300">Record the current, measured values. Every submitted inspection is saved to this vehicle’s secure history.</p>{error && <p role="alert" className="mt-5 rounded-xl bg-red-500/10 p-4 text-red-200">{error}</p>}{success && <p role="status" className="mt-5 rounded-xl bg-emerald-400/10 p-4 text-emerald-200">{success}</p>}<div className="mt-7 space-y-5"><section className="rounded-3xl border border-white/10 bg-slate-900 p-6"><h2 className="text-xl font-semibold">Engine</h2><div className="mt-4 grid gap-4 md:grid-cols-3">{field('engineTemperature','Engine temperature (°C)')}{field('engineRpm','Engine RPM','number','1')}<label className="text-sm text-slate-300">Engine oil level<select required value={values.engineOilLevel} onChange={e=>update('engineOilLevel',e.target.value)} className="input"><option value="normal">Normal</option><option value="low">Low</option></select></label></div></section><section className="rounded-3xl border border-white/10 bg-slate-900 p-6"><h2 className="text-xl font-semibold">Battery & fuel</h2><div className="mt-4 grid gap-4 md:grid-cols-4">{field('batteryVoltage','Battery voltage (V)')}{field('batteryHealth','Battery health (%)')}{field('fuelLevel','Fuel level (%)')}{field('averageFuelEfficiency','Fuel efficiency (km/l)')}</div></section><section className="rounded-3xl border border-white/10 bg-slate-900 p-6"><h2 className="text-xl font-semibold">Brakes, tyres & cooling</h2><div className="mt-4 grid gap-4 md:grid-cols-4">{field('brakeCondition','Brake condition (%)')}{field('frontLeft','Front left tyre (psi)')}{field('frontRight','Front right tyre (psi)')}{field('rearLeft','Rear left tyre (psi)')}{field('rearRight','Rear right tyre (psi)')}{field('tyreWear','Tyre wear (%)')}<label className="text-sm text-slate-300">Coolant level<select required value={values.coolantLevel} onChange={e=>update('coolantLevel',e.target.value)} className="input"><option value="normal">Normal</option><option value="low">Low</option></select></label></div></section><section className="rounded-3xl border border-white/10 bg-slate-900 p-6"><h2 className="text-xl font-semibold">General</h2><div className="mt-4 grid gap-4 md:grid-cols-2">{field('currentOdometer','Current odometer (km)')}{field('lastServiceDate','Last service date','date')}</div></section></div><button disabled={saving} className="mt-7 rounded-full bg-cyan-400 px-6 py-3 font-semibold text-slate-950 disabled:opacity-60">{saving ? 'Saving inspection…' : 'Save inspection'}</button></form></main>;
}
export default InspectionPage;
